"""
This type stub file was generated by pyright.
"""

camelcase_to_kebabcase = ...
class Baseevents:
    def __init__(self) -> None:
        ...
    
    def input(self, data): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getattr__(self, item): # -> Callable[[], Any]:
        ...
    


class Baserequests:
    def __init__(self, **kwargs) -> None:
        ...
    
    def data(self): # -> dict[Any, Any]:
        ...
    
    def input(self, data, status): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getattr__(self, item): # -> Callable[[], Any]:
        ...
    


class ClassFactory:
    cache = ...
    def __init__(self, base_class) -> None:
        ...
    
    def __getattr__(self, item): # -> Any:
        ...
    


