"""
This type stub file was generated by pyright.
"""

import threading

LOG = ...
class obsws:
    """
    Core class for using obs-websocket-py

    Simple usage: (v5 api)
        >>> from obswebsocket import obsws, requests
        >>> client = obsws("localhost", 4455, "secret")
        >>> client.connect()
        >>> client.call(requests.GetVersion()).getObsVersion()
        '29.0.0'
        >>> client.disconnect()

    Legacy usage: (v4 api)
        >>> from obswebsocket import obsws, requests
        >>> client = obsws("localhost", 4444, "secret", legacy=True)
        >>> client.connect()
        >>> client.call(requests.GetVersion()).getObsStudioVersion()
        '25.0.0'
        >>> client.disconnect()

    For advanced usage, including events callback, see the 'samples' directory.
    """
    def __init__(self, host=..., port=..., password=..., legacy=..., timeout=..., authreconnect=..., on_connect=..., on_disconnect=...) -> None:
        """
        Construct a new obsws wrapper

        :param host: Hostname to connect to
        :param port: TCP Port to connect to (Default is 4444)
        :param password: Password for the websocket server (Leave this field empty if auth is not enabled)
        :param legacy: Server is using old obs-websocket protocol (v4). Default is v5 (False) except if port is 4444.
        :param timeout: How much seconds to wait for an answer after sending a request.
        :param authreconnect: Try to reconnect if websocket is closed, value is number of seconds between attemps.
        :param on_connect: Function to call after successful connect, with parameter (obsws)
        :param on_disconnect: Function to call after successful disconnect, with parameter (obsws)
        """
        ...
    
    def connect(self): # -> None:
        """
        Connect to the websocket server

        :return: Nothing
        """
        ...
    
    def reconnect(self): # -> None:
        """
        Restart the connection to the websocket server

        :return: Nothing
        """
        ...
    
    def disconnect(self): # -> None:
        """
        Disconnect from websocket server

        :return: Nothing
        """
        ...
    
    def call(self, obj): # -> Baserequests:
        """
        Make a call to the OBS server through the Websocket.

        :param obj: Request (class from obswebsocket.requests module) to send
            to the server.
        :return: Request object populated with response data.
        """
        ...
    
    def register(self, func, event=...): # -> None:
        """
        Register a new hook in the websocket client

        :param func: Callback function pointer for the hook
        :param event: Event (class from obswebsocket.events module) to trigger
            the hook on. Default is None, which means trigger on all events.
        :return: Nothing
        """
        ...
    
    def unregister(self, func, event=...): # -> None:
        """
        Unregister a new hook in the websocket client

        :param func: Callback function pointer for the hook
        :param event: Event (class from obswebsocket.events module) which
            triggered the hook on. Default is None, which means unregister this
            function for all events.
        :return: Nothing
        """
        ...
    


class RecvThread(threading.Thread):
    def __init__(self, core) -> None:
        ...
    
    def run(self): # -> None:
        ...
    
    def build_event(self, data): # -> Any:
        ...
    


class ReconnectThread(threading.Thread):
    def __init__(self, core) -> None:
        ...
    
    def run(self): # -> None:
        ...
    


class EventManager:
    def __init__(self) -> None:
        ...
    
    def register(self, callback, trigger): # -> None:
        ...
    
    def unregister(self, callback, trigger): # -> None:
        ...
    
    def trigger(self, data): # -> None:
        ...
    


